---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 6.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    provider: "google"
    fqdnTemplate: "{{.Name}}.gcp01.work.terrible.systems"
    domainFilters: [
      "gcp01.work.terrible.systems"
    ]
    google.project: "dlancashire-k8s-dev"
    serviceAccount.annotations:
      iam.gke.io/gke-metadata-server-enabled: "true"

